name: auto approve
on: pull_request
jobs:
  merge:
    runs-on: ubuntu-latest
    if: github.actor == 'self-hosted-renovate-4sjvn[bot]' && endsWith(github.head_ref, '_am')
    steps:
      - name: generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          private_key: ${{ secrets.ACD_PRIVATE_KEY }}
          app_id: ${{ secrets.ACD_APP_ID }}
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - env:
          GH_TOKEN:  ${{ steps.generate_token.outputs.token }}
        run: |
          gh pr review --approve
          gh pr merge --merge --auto
